### ISSUE TITLE
Can't find npm module 'common-tags'. Did you forget to call 'Npm.depends' in package.js

### ISSUE THREAD

**Issue by Falieson** [abernix/meteord#21]
I get this same error when I use node-8.4.0-base in MUP or -onbuild following the README.

I tried the spaceglue version of 8.4.0-onbuild, but no success their either

Thanks for any help...

```
FROM abernix/meteord:node-8.4.0-onbuild
```

```
Error: Can't find npm module 'common-tags'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
    at Object.require (/built_app/programs/server/boot.js:266:17)
    at makeInstallerOptions.fallback (packages/modules-runtime.js:641:18)
    at require (packages/modules-runtime.js:234:16)
    at index.js (packages/modules.js:396:19)
    at fileEvaluate (packages/modules-runtime.js:333:9)
    at require (packages/modules-runtime.js:228:16)
    at package-scripts.js (package-scripts.js:1:32)
    at fileEvaluate (packages/modules-runtime.js:333:9)
    at require (packages/modules-runtime.js:228:16)
    at /built_app/programs/server/app/app.js:432:1
```

**Comment by abernix** [comment]
Please provide a reproduction.

**Comment by Falieson** [comment]
I tried reproducing the error by doing create -full -release=1.6-beta24 ... etc. and building w/ the meteord docker image. It worked fine so it must be something in my meteor code.
I thought maybe deleting my .meteor/local and restarting but as I expected that didn't change the results.

I may retry this dockerization path by transplanting my meteor code into a fresh bare install (its a very small codebase) and see if I still have the issue;
but for now I'm going to proceed w/o docker - i'm not ready for prod yet anyways.

Thanks
