### ISSUE TITLE
Error when building with OnBuild image

### ISSUE THREAD

**Issue by gl-lamhnguyen** [abernix/meteord#33]
Missing some module:

```
Errors prevented bundling:
While minifying app stylesheet:
module.js:536:15: Cannot find module 'autoprefixer'
at Function.Module._resolveFilename (module.js:536:15)
at Function.resolve (internal/module.js:18:19)
at Object.require (/tools/isobuild/bundler.js:1873:34)
at packages/minifier-postcss/plugin/minify-css.js:52:37
at Array.forEach (<anonymous>)
at getPostCSSPlugins (packages/minifier-postcss/plugin/minify-css.js:51:43)
at packages/minifier-postcss/plugin/minify-css.js:155:36
at Array.map (<anonymous>)
at mergeCss (packages/minifier-postcss/plugin/minify-css.js:139:23)
at CssToolsMinifier.processFilesForBundle
(packages/minifier-postcss/plugin/minify-css.js:109:18)
```

Not sure how I could run `npm install` before the base image start building the project.

**Comment by abernix** [comment]
Closing as there's not enough detail here to determine if this is a problem with the image or with Meteor itself.
