### ISSUE TITLE
mup deploy failed when sharp is installed.

### ISSUE THREAD

**Issue by pawa-wayne** [abernix/meteord#53]
I have a simple meteor app and 
have sharp installed by
meteor npm install sharp
it works fine on local run.

when I try to deploy by running mup deploy. it fails.
meteor : Meteor 1.10.2
mup docker : abernix/meteord:node-12.16.1-base

is there anyway I can get this to work?  

the mup deloy logs are: 

x Prepare Bundle: FAILED
        
              ------------------------------------STDERR------------------------------------
              The command '/bin/sh -c cd /built_app/programs/server &&     npm install --unsafe-perm' returned a non-zero code: 1
        
        real    1m58.989s
        user    0m2.560s
        sys     0m2.776s
        
              ------------------------------------STDOUT------------------------------------
              so: No such file or directory
        g++: error: ../vendor/lib/libharfbuzz.so: No such file or directory
        g++: error: ../vendor/lib/libjpeg.so: No such file or directory
        g++: error: ../vendor/lib/liblcms2.so: No such file or directory
        g++: error: ../vendor/lib/liborc-0.4.so: No such file or directory
        g++: error: ../vendor/lib/libpango-1.0.so: No such file or directory
        g++: error: ../vendor/lib/libpangocairo-1.0.so: No such file or directory
        g++: error: ../vendor/lib/libpangoft2-1.0.so: No such file or directory
        g++: error: ../vendor/lib/libpixman-1.so: No such file or directory
        g++: error: ../vendor/lib/libpng.so: No such file or directory
        g++: error: ../vendor/lib/librsvg-2.so: No such file or directory
        g++: error: ../vendor/lib/libtiff.so: No such file or directory
        g++: error: ../vendor/lib/libwebp.so: No such file or directory
        g++: error: ../vendor/lib/libwebpdemux.so: No such file or directory
        g++: error: ../vendor/lib/libwebpmux.so: No such file or directory
        g++: error: ../vendor/lib/libxml2.so: No such file or directory
        g++: error: ../vendor/lib/libz.so: No such file or directory
        sharp.target.mk:201: recipe for target 'Release/obj.target/sharp.node' failed
        make: *** [Release/obj.target/sharp.node] Error 1
        make: Leaving directory '/built_app/programs/server/npm/node_modules/sharp/build'
        gyp ERR! build error 
        gyp ERR! stack Error: `make` failed with exit code: 2
        gyp ERR! stack     at ChildProcess.onExit (/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
        gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
        gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
        gyp ERR! System Linux 4.4.0-1107-aws
        gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
        gyp ERR! cwd /built_app/programs/server/npm/node_modules/sharp
        gyp ERR! node -v v12.16.1
        gyp ERR! node-gyp -v v5.0.7
        gyp ERR! not ok 
        npm ERR! code ELIFECYCLE
        npm ERR! errno 1
        npm ERR! sharp@0.25.4 install: `(node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)`
        npm ERR! Exit status 1
        npm ERR! 
        npm ERR! Failed at the sharp@0.25.4 install script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
        
        npm ERR! A complete log of this run can be found in:
        npm ERR!     /root/.npm/_logs/2020-08-13T08_47_18_935Z-debug.log
        npm ERR! code ELIFECYCLE
        npm ERR! errno 1
        npm ERR! meteor-dev-bundle@ install: `node npm-rebuild.js`
        npm ERR! Exit status 1
        npm ERR! 
        npm ERR! Failed at the meteor-dev-bundle@ install script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
        
        npm ERR! A complete log of this run can be found in:
        npm ERR!     /root/.npm/_logs/2020-08-13T08_47_18_993Z-debug.log
        
              ------------------------------------------------------------------------------

**Comment by pawa-wayne** [comment]
or is there anyway I can build my own docker image for mup ?

**Comment by iok97531** [comment]
I think you should install sharp for linux with this command
meteor npm install --arch=x64 --platform=linux sharp
